# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'paredesexternas.ui'
##
## Created by: Qt User Interface Compiler version 6.1.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *  # type: ignore
from PySide6.QtGui import *  # type: ignore
from PySide6.QtWidgets import *  # type: ignore


class Ui_ParedesExternas(object):
    def setupUi(self, ParedesExternas):
        if not ParedesExternas.objectName():
            ParedesExternas.setObjectName(u"ParedesExternas")
        ParedesExternas.resize(719, 652)
        self.plainTextEdit = QPlainTextEdit(ParedesExternas)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(280, 150, 131, 31))
        self.textBrowser = QTextBrowser(ParedesExternas)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(280, 110, 131, 31))
        self.textBrowser.setFrameShape(QFrame.WinPanel)
        self.textBrowser.setLineWidth(4)
        self.plainTextEdit_2 = QPlainTextEdit(ParedesExternas)
        self.plainTextEdit_2.setObjectName(u"plainTextEdit_2")
        self.plainTextEdit_2.setGeometry(QRect(500, 150, 131, 31))
        self.textBrowser_2 = QTextBrowser(ParedesExternas)
        self.textBrowser_2.setObjectName(u"textBrowser_2")
        self.textBrowser_2.setGeometry(QRect(500, 110, 131, 31))
        self.textBrowser_2.setFrameShape(QFrame.WinPanel)
        self.textBrowser_2.setLineWidth(4)
        self.textBrowser_3 = QTextBrowser(ParedesExternas)
        self.textBrowser_3.setObjectName(u"textBrowser_3")
        self.textBrowser_3.setGeometry(QRect(40, 200, 131, 31))
        self.textBrowser_3.setFrameShape(QFrame.WinPanel)
        self.textBrowser_3.setLineWidth(4)
        self.comboBox = QComboBox(ParedesExternas)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(40, 240, 131, 31))
        self.textBrowser_4 = QTextBrowser(ParedesExternas)
        self.textBrowser_4.setObjectName(u"textBrowser_4")
        self.textBrowser_4.setGeometry(QRect(280, 200, 131, 31))
        self.textBrowser_4.setFrameShape(QFrame.WinPanel)
        self.textBrowser_4.setLineWidth(4)
        self.comboBox_2 = QComboBox(ParedesExternas)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(280, 240, 131, 31))
        self.pushButton = QPushButton(ParedesExternas)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(510, 370, 171, 24))
        self.textBrowser_5 = QTextBrowser(ParedesExternas)
        self.textBrowser_5.setObjectName(u"textBrowser_5")
        self.textBrowser_5.setGeometry(QRect(250, 30, 191, 41))
        self.pushButton_2 = QPushButton(ParedesExternas)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(510, 410, 171, 24))
        self.label = QLabel(ParedesExternas)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(60, 330, 301, 251))
        self.label.setPixmap(QPixmap(u"rdv.png"))
        self.label.setScaledContents(True)
        self.radioButton = QRadioButton(ParedesExternas)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setEnabled(True)
        self.radioButton.setGeometry(QRect(210, 310, 16, 16))
        self.radioButton.setChecked(True)
        self.radioButton_2 = QRadioButton(ParedesExternas)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setGeometry(QRect(280, 330, 16, 16))
        self.radioButton_3 = QRadioButton(ParedesExternas)
        self.radioButton_3.setObjectName(u"radioButton_3")
        self.radioButton_3.setGeometry(QRect(330, 360, 16, 16))
        self.radioButton_4 = QRadioButton(ParedesExternas)
        self.radioButton_4.setObjectName(u"radioButton_4")
        self.radioButton_4.setGeometry(QRect(350, 410, 16, 16))
        self.radioButton_5 = QRadioButton(ParedesExternas)
        self.radioButton_5.setObjectName(u"radioButton_5")
        self.radioButton_5.setGeometry(QRect(370, 460, 16, 16))
        self.radioButton_6 = QRadioButton(ParedesExternas)
        self.radioButton_6.setObjectName(u"radioButton_6")
        self.radioButton_6.setGeometry(QRect(350, 510, 16, 16))
        self.radioButton_7 = QRadioButton(ParedesExternas)
        self.radioButton_7.setObjectName(u"radioButton_7")
        self.radioButton_7.setGeometry(QRect(320, 550, 16, 16))
        self.radioButton_8 = QRadioButton(ParedesExternas)
        self.radioButton_8.setObjectName(u"radioButton_8")
        self.radioButton_8.setGeometry(QRect(260, 580, 16, 16))
        self.radioButton_9 = QRadioButton(ParedesExternas)
        self.radioButton_9.setObjectName(u"radioButton_9")
        self.radioButton_9.setGeometry(QRect(210, 590, 16, 16))
        self.radioButton_10 = QRadioButton(ParedesExternas)
        self.radioButton_10.setObjectName(u"radioButton_10")
        self.radioButton_10.setGeometry(QRect(150, 580, 16, 16))
        self.radioButton_11 = QRadioButton(ParedesExternas)
        self.radioButton_11.setObjectName(u"radioButton_11")
        self.radioButton_11.setGeometry(QRect(100, 550, 16, 16))
        self.radioButton_12 = QRadioButton(ParedesExternas)
        self.radioButton_12.setObjectName(u"radioButton_12")
        self.radioButton_12.setGeometry(QRect(70, 510, 16, 16))
        self.radioButton_13 = QRadioButton(ParedesExternas)
        self.radioButton_13.setObjectName(u"radioButton_13")
        self.radioButton_13.setGeometry(QRect(40, 460, 16, 16))
        self.radioButton_14 = QRadioButton(ParedesExternas)
        self.radioButton_14.setObjectName(u"radioButton_14")
        self.radioButton_14.setGeometry(QRect(60, 400, 16, 16))
        self.radioButton_15 = QRadioButton(ParedesExternas)
        self.radioButton_15.setObjectName(u"radioButton_15")
        self.radioButton_15.setGeometry(QRect(100, 350, 16, 16))
        self.radioButton_16 = QRadioButton(ParedesExternas)
        self.radioButton_16.setObjectName(u"radioButton_16")
        self.radioButton_16.setGeometry(QRect(150, 320, 16, 16))
        self.textBrowser_7 = QTextBrowser(ParedesExternas)
        self.textBrowser_7.setObjectName(u"textBrowser_7")
        self.textBrowser_7.setGeometry(QRect(500, 200, 131, 31))
        self.textBrowser_7.setFrameShape(QFrame.WinPanel)
        self.textBrowser_7.setLineWidth(4)
        self.plainTextEdit_4 = QPlainTextEdit(ParedesExternas)
        self.plainTextEdit_4.setObjectName(u"plainTextEdit_4")
        self.plainTextEdit_4.setGeometry(QRect(500, 240, 131, 31))
        self.pushButton_3 = QPushButton(ParedesExternas)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(510, 450, 171, 24))
        self.plainTextEdit_5 = QPlainTextEdit(ParedesExternas)
        self.plainTextEdit_5.setObjectName(u"plainTextEdit_5")
        self.plainTextEdit_5.setGeometry(QRect(520, 490, 151, 51))
        self.pushButton_4 = QPushButton(ParedesExternas)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(510, 330, 171, 24))
        self.comboBox_3 = QComboBox(ParedesExternas)
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(40, 150, 131, 31))
        self.comboBox_3.setEditable(False)
        self.textBrowser_6 = QTextBrowser(ParedesExternas)
        self.textBrowser_6.setObjectName(u"textBrowser_6")
        self.textBrowser_6.setGeometry(QRect(40, 110, 131, 31))
        self.textBrowser_6.setFrameShape(QFrame.WinPanel)
        self.textBrowser_6.setLineWidth(4)
        self.pushButton_5 = QPushButton(ParedesExternas)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(30, 40, 171, 24))
        self.label.raise_()
        self.plainTextEdit.raise_()
        self.textBrowser.raise_()
        self.plainTextEdit_2.raise_()
        self.textBrowser_2.raise_()
        self.textBrowser_3.raise_()
        self.comboBox.raise_()
        self.textBrowser_4.raise_()
        self.comboBox_2.raise_()
        self.pushButton.raise_()
        self.textBrowser_5.raise_()
        self.pushButton_2.raise_()
        self.radioButton.raise_()
        self.radioButton_2.raise_()
        self.radioButton_3.raise_()
        self.radioButton_4.raise_()
        self.radioButton_5.raise_()
        self.radioButton_6.raise_()
        self.radioButton_7.raise_()
        self.radioButton_8.raise_()
        self.radioButton_9.raise_()
        self.radioButton_10.raise_()
        self.radioButton_11.raise_()
        self.radioButton_12.raise_()
        self.radioButton_13.raise_()
        self.radioButton_14.raise_()
        self.radioButton_15.raise_()
        self.radioButton_16.raise_()
        self.textBrowser_7.raise_()
        self.plainTextEdit_4.raise_()
        self.pushButton_3.raise_()
        self.plainTextEdit_5.raise_()
        self.pushButton_4.raise_()
        self.comboBox_3.raise_()
        self.textBrowser_6.raise_()
        self.pushButton_5.raise_()

        self.retranslateUi(ParedesExternas)

        QMetaObject.connectSlotsByName(ParedesExternas)
    # setupUi

    def retranslateUi(self, ParedesExternas):
        ParedesExternas.setWindowTitle(QCoreApplication.translate("ParedesExternas", u"Dialog", None))
        self.textBrowser.setHtml(QCoreApplication.translate("ParedesExternas", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt;\">Espessura [m]</span></p></body></html>", None))
        self.textBrowser_2.setHtml(QCoreApplication.translate("ParedesExternas", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt;\">Largura [m]</span></p></body></html>", None))
        self.textBrowser_3.setHtml(QCoreApplication.translate("ParedesExternas", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt;\">Tipo de Material</span></p></body></html>", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("ParedesExternas", u"BC_ext", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("ParedesExternas", u"BC_int", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("ParedesExternas", u"A", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("ParedesExternas", u"G15", None))
        self.comboBox.setItemText(4, QCoreApplication.translate("ParedesExternas", u"LR50", None))
        self.comboBox.setItemText(5, QCoreApplication.translate("ParedesExternas", u"LR70", None))
        self.comboBox.setItemText(6, QCoreApplication.translate("ParedesExternas", u"LR100", None))
        self.comboBox.setItemText(7, QCoreApplication.translate("ParedesExternas", u"LV25", None))
        self.comboBox.setItemText(8, QCoreApplication.translate("ParedesExternas", u"LV50", None))
        self.comboBox.setItemText(9, QCoreApplication.translate("ParedesExternas", u"LV70", None))
        self.comboBox.setItemText(10, QCoreApplication.translate("ParedesExternas", u"LV100", None))
        self.comboBox.setItemText(11, QCoreApplication.translate("ParedesExternas", u"LM60", None))
        self.comboBox.setItemText(12, QCoreApplication.translate("ParedesExternas", u"PE", None))
        self.comboBox.setItemText(13, QCoreApplication.translate("ParedesExternas", u"PRE", None))
        self.comboBox.setItemText(14, QCoreApplication.translate("ParedesExternas", u"T26", None))
        self.comboBox.setItemText(15, QCoreApplication.translate("ParedesExternas", u"T24", None))
        self.comboBox.setItemText(16, QCoreApplication.translate("ParedesExternas", u"T22", None))
        self.comboBox.setItemText(17, QCoreApplication.translate("ParedesExternas", u"V03", None))
        self.comboBox.setItemText(18, QCoreApplication.translate("ParedesExternas", u"V06", None))
        self.comboBox.setItemText(19, QCoreApplication.translate("ParedesExternas", u"VD", None))
        self.comboBox.setItemText(20, QCoreApplication.translate("ParedesExternas", u"AA", None))
        self.comboBox.setItemText(21, QCoreApplication.translate("ParedesExternas", u"TI26", None))
        self.comboBox.setItemText(22, QCoreApplication.translate("ParedesExternas", u"TI24", None))
        self.comboBox.setItemText(23, QCoreApplication.translate("ParedesExternas", u"TI22", None))
        self.comboBox.setItemText(24, QCoreApplication.translate("ParedesExternas", u"DD", None))
        self.comboBox.setItemText(25, QCoreApplication.translate("ParedesExternas", u"DV", None))
        self.comboBox.setItemText(26, QCoreApplication.translate("ParedesExternas", u"DLM", None))
        self.comboBox.setItemText(27, QCoreApplication.translate("ParedesExternas", u"FF", None))
        self.comboBox.setItemText(28, QCoreApplication.translate("ParedesExternas", u"FG", None))
        self.comboBox.setItemText(29, QCoreApplication.translate("ParedesExternas", u"PE", None))
        self.comboBox.setItemText(30, QCoreApplication.translate("ParedesExternas", u"CAFF", None))
        self.comboBox.setItemText(31, QCoreApplication.translate("ParedesExternas", u"CAFG", None))
        self.comboBox.setItemText(32, QCoreApplication.translate("ParedesExternas", u"CAPE", None))
        self.comboBox.setItemText(33, QCoreApplication.translate("ParedesExternas", u"CAT", None))
        self.comboBox.setItemText(34, QCoreApplication.translate("ParedesExternas", u"CATI", None))
        self.comboBox.setItemText(35, QCoreApplication.translate("ParedesExternas", u"FFCAT", None))
        self.comboBox.setItemText(36, QCoreApplication.translate("ParedesExternas", u"FGCAT", None))
        self.comboBox.setItemText(37, QCoreApplication.translate("ParedesExternas", u"FFCATI", None))
        self.comboBox.setItemText(38, QCoreApplication.translate("ParedesExternas", u"FGCATI", None))

        self.textBrowser_4.setHtml(QCoreApplication.translate("ParedesExternas", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt;\">Grupo</span></p></body></html>", None))
        self.comboBox_2.setItemText(0, QCoreApplication.translate("ParedesExternas", u"A", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("ParedesExternas", u"B", None))
        self.comboBox_2.setItemText(2, QCoreApplication.translate("ParedesExternas", u"C", None))
        self.comboBox_2.setItemText(3, QCoreApplication.translate("ParedesExternas", u"D", None))
        self.comboBox_2.setItemText(4, QCoreApplication.translate("ParedesExternas", u"E", None))
        self.comboBox_2.setItemText(5, QCoreApplication.translate("ParedesExternas", u"F", None))
        self.comboBox_2.setItemText(6, QCoreApplication.translate("ParedesExternas", u"G", None))

        self.pushButton.setText(QCoreApplication.translate("ParedesExternas", u"Voltar para o Menu", None))
        self.textBrowser_5.setHtml(QCoreApplication.translate("ParedesExternas", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:700;\">Paredes Externas</span></p></body></html>", None))
        self.pushButton_2.setText(QCoreApplication.translate("ParedesExternas", u"Adicionar Parede", None))
        self.label.setText("")
        self.radioButton.setText("")
        self.radioButton_2.setText("")
        self.radioButton_3.setText("")
        self.radioButton_4.setText("")
        self.radioButton_5.setText("")
        self.radioButton_6.setText("")
        self.radioButton_7.setText("")
        self.radioButton_8.setText("")
        self.radioButton_9.setText("")
        self.radioButton_10.setText("")
        self.radioButton_11.setText("")
        self.radioButton_12.setText("")
        self.radioButton_13.setText("")
        self.radioButton_14.setText("")
        self.radioButton_15.setText("")
        self.radioButton_16.setText("")
        self.textBrowser_7.setHtml(QCoreApplication.translate("ParedesExternas", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt;\">\u00c1rea de Janelas</span></p></body></html>", None))
        self.pushButton_3.setText(QCoreApplication.translate("ParedesExternas", u"Calcular", None))
        self.pushButton_4.setText(QCoreApplication.translate("ParedesExternas", u"Carregar \u00faltimos dados", None))
        self.textBrowser_6.setHtml(QCoreApplication.translate("ParedesExternas", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt;\">TAG</span></p></body></html>", None))
        self.pushButton_5.setText(QCoreApplication.translate("ParedesExternas", u"Atualizar", None))
    # retranslateUi

